# Created by irfan.maulana on 08/16/2016.
swagger: "2.0"
info:
  version: "0.0.1"
  title: Pocketloan Api Documentation
# during dev, should point to your local machine
host: localhost: 3001
# basePath prefixes all resource paths 
basePath: /
# 
schemes:
  - https
# format of bodies a client can send (Content-Type)
consumes:
  - application/json
# format of the responses to the client (Accepts)
produces:
  - application/json
paths:
  /v1/openapi:
    get:
      description: Returns the api documentation of the application
      responses:
        "200":
          description: Success
  /v1/health:
    get:
      description: Returns the status or health of the application
      responses:
        "200":
          description: Success
          schema:
            # a pointer to a definition
            $ref: "#/definitions/HealthResponse"
  /v1/users/get:
    get:
      description: Returns list of Users
      responses:
        "200":
          description: Success
          schema:
            # a pointer to a definition
            $ref: "#/definitions/ProductsResponse"
        # responses may fall through to errors
        default:
          description: Error
          schema:
            $ref: "#/definitions/GeneralErrorResponse" 
  /v1/users/get/{id}:
    get:
      description: Returns product by id
      parameters:
        - name: id
          description: id of product will be select
          type: number
          in: path
          required: true
      responses:
        "200":
          description: Success
          schema:
            # a pointer to a definition
            $ref: "#/definitions/ProductResponse"
        # responses may fall through to errors
        default:
          description: Error
          schema:
            $ref: "#/definitions/GeneralErrorResponse"

    patch:
      description: Update data product by id
      parameters:
        - name: id
          description: id of product will be updated
          type: number
          in: path
          required: true
        - name: product
          description: Product information will be updated
          in: body
          required: true
          schema: 
            $ref: "#/definitions/ProductNoId"
      responses:
        "200":
          description: Success
          schema:
            # a pointer to a definition
            $ref: "#/definitions/ProductResponse"
        # responses may fall through to errors
        default:
          description: Error
          schema:
            $ref: "#/definitions/GeneralErrorResponse"

    delete:
      description: Delete data product by id
      parameters:
        - name: id
          description: id of product will be deleted
          type: number
          in: path
          required: true
      responses:
        "200":
          description: Success
          schema:
            # a pointer to a definition
            $ref: "#/definitions/ProductResponse"
        # responses may fall through to errors
        default:
          description: Error
          schema:
            $ref: "#/definitions/GeneralErrorResponse"

  /swagger:
    x-swagger-pipe: swagger_raw
# complex objects have schema definitions
definitions:

  Product:
    properties:
      _id:
        type: string
        format: uid
        readOnly: true
      userName:
        type: string
        format: uid
        readOnly: true
      firstName:
        type: string
        readOnly: true
      lastName:
        type: string
        readOnly: true
      email:
        type: string
        readOnly: true
      password:
        type: string
        readOnly: true
      sinNumber:
        type: string
        readOnly: true
      sex:
        type: string
        readOnly: true
      creditCard:
        type: string
        readOnly: true
      phoneNumber:
        type: string
        readOnly: true
      avatar:
        type: string
        readOnly: true
      dateCreated:
        type: string
        format: date
        readOnly: true
      dateUpdated:
        type: string
        format: date
        readOnly: true
      rating:
        type: string
        readOnly: true
      token:
        type: string
        readOnly: true
      verified:
        type: boolean
        readOnly: true
      accountType:
        type: string
        readOnly: true
      age:
        type: string
        readOnly: true

        
  HealthResponse:
    properties:
      message:
        type: string
      status:
        type: string
        
  ProductNoId:
    properties:
      title:
        type: string
      description:
        type: string
      price:
        type: number
        
  ProductsResponse:
    required:
      - result
      - products
    properties:
      result:
        type: boolean
        default: true
      products:
        type: array
        items:
          $ref: "#/definitions/Product"
          
  ProductResponse:
    required:
      - result
      - product
    properties:
      result:
        type: boolean
        default: true
      product:
        $ref: "#/definitions/Product"
          
  GeneralErrorResponse:
    required:
      - message
      - status
      - success
    properties:
      message:
        type: string
      status:
        type: string
      success:
        type: boolean
        default: false